In [1]:
5+5

10

In [2]:
s="hi there sam"
print(s.split())

['hi', 'there', 'sam']


In [4]:
print(" The diameter of earth is,{}"
      .format("12472"))


 The diameter of earth is,12472


In [8]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [9]:
import numpy as np

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


In [13]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:

import pandas as pd


data = [['tom', 10], ['nick', 15], ['juli', 14]]


df = pd.DataFrame(data, columns=['Name', 'Age'])


df


Name  Age
0   tom   10
1  nick   15
2  juli   14

In [27]:
from datetime import timedelta, date

def daterange(date1, date2):
    for n in range(int ((date2 - date1).days)+1):
        yield date1 + timedelta(n)

start_dt = date(2023, 1, 1)
end_dt = date(2023, 2, 10)
for dt in daterange(start_dt, end_dt):
    print(dt.strftime("%Y-%m-%d"))

2023-01-01
2023-01-02
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-07
2023-01-08
2023-01-09
2023-01-10
2023-01-11
2023-01-12
2023-01-13
2023-01-14
2023-01-15
2023-01-16
2023-01-17
2023-01-18
2023-01-19
2023-01-20
2023-01-21
2023-01-22
2023-01-23
2023-01-24
2023-01-25
2023-01-26
2023-01-27
2023-01-28
2023-01-29
2023-01-30
2023-01-31
2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10


In [31]:
import pandas as pd
	
# List1
lst = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
	
df = pd.DataFrame(lst, columns =['s.no', 'name', 'Age'],
										dtype = float)
print(df)





   s.no name   Age
0   1.0  aaa  22.0
1   2.0  bbb  25.0
2   3.0  ccc  24.0


C:\Users\ASUS\AppData\Local\Temp\ipykernel_16448\636417943.py:6: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  df = pd.DataFrame(lst, columns =['s.no', 'name', 'Age'],
